last_words = [
    {"it": "buongiorno", "pl": "dzień dobry", "lvl": 0, "learned": False},
    {"it": "grazie mille", "pl": "dziękuję bardzo", "lvl": 0, "learned": False},
    {"it": "per favore", "pl": "proszę", "lvl": 0, "learned": False},
    {"it": "prego", "pl": "nie ma za co", "lvl": 0, "learned": False},
    {"it": "scusa", "pl": "przepraszam", "lvl": 0, "learned": False},
    {"it": "come stai", "pl": "jak się masz", "lvl": 0, "learned": False},
    {"it": "molto bene", "pl": "bardzo dobrze", "lvl": 0, "learned": False},
    {"it": "piacere", "pl": "miło mi", "lvl": 0, "learned": False},
    {"it": "arrivederci", "pl": "do widzenia", "lvl": 0, "learned": False},
    {"it": "ciao", "pl": "cześć", "lvl": 0, "learned": False},
    {"it": "arancini", "pl": "smażone kulki ryżowe", "lvl": 0, "learned": False},
    {"it": "cannolo", "pl": "rurka z kremem", "lvl": 0, "learned": False},
    {"it": "gelato", "pl": "lody", "lvl": 0, "learned": False},
    {"it": "pizza", "pl": "pizza", "lvl": 0, "learned": False},
    {"it": "pasta", "pl": "makaron", "lvl": 0, "learned": False},
    {"it": "acqua", "pl": "woda", "lvl": 0, "learned": False},
    {"it": "birra", "pl": "piwo", "lvl": 0, "learned": False},
    {"it": "vino", "pl": "wino", "lvl": 0, "learned": False},
    {"it": "colazione", "pl": "śniadanie", "lvl": 0, "learned": False},
    {"it": "pranzo", "pl": "obiad", "lvl": 0, "learned": False},
    {"it": "cena", "pl": "kolacja", "lvl": 0, "learned": False},
    {"it": "il conto", "pl": "rachunek", "lvl": 0, "learned": False},
    {"it": "mare", "pl": "morze", "lvl": 0, "learned": False},
    {"it": "sole", "pl": "słońce", "lvl": 0, "learned": False},
    {"it": "spiaggia", "pl": "plaża", "lvl": 0, "learned": False},
    {"it": "piazza", "pl": "plac", "lvl": 0, "learned": False},
    {"it": "strada", "pl": "ulica", "lvl": 0, "learned": False},
    {"it": "stazione", "pl": "stacja", "lvl": 0, "learned": False},
    {"it": "aeroporto", "pl": "lotnisko", "lvl": 0, "learned": False},
    {"it": "biglietto", "pl": "bilet", "lvl": 0, "learned": False},
    {"it": "treno", "pl": "pociąg", "lvl": 0, "learned": False},
    {"it": "macchina", "pl": "samochód", "lvl": 0, "learned": False},
    {"it": "lavoro", "pl": "praca", "lvl": 0, "learned": False},
    {"it": "ufficio", "pl": "biuro", "lvl": 0, "learned": False},
    {"it": "computer", "pl": "komputer", "lvl": 0, "learned": False},
    {"it": "studio", "pl": "studiowanie", "lvl": 0, "learned": False},
    {"it": "imparare", "pl": "uczyć się", "lvl": 0, "learned": False},
    {"it": "scrivere", "pl": "pisać", "lvl": 0, "learned": False},
    {"it": "leggere", "pl": "czytać", "lvl": 0, "learned": False},
    {"it": "programmare", "pl": "programować", "lvl": 0, "learned": False},
    {"it": "oggi", "pl": "dzisiaj", "lvl": 0, "learned": False},
    {"it": "domani", "pl": "jutro", "lvl": 0, "learned": False},
    {"it": "ieri", "pl": "wczoraj", "lvl": 0, "learned": False},
    {"it": "ora", "pl": "godzina", "lvl": 0, "learned": False},
    {"it": "settimana", "pl": "tydzień", "lvl": 0, "learned": False},
    {"it": "uno", "pl": "jeden", "lvl": 0, "learned": False},
    {"it": "due", "pl": "dwa", "lvl": 0, "learned": False},
    {"it": "tre", "pl": "trzy", "lvl": 0, "learned": False},
    {"it": "quattro", "pl": "cztery", "lvl": 0, "learned": False},
    {"it": "cinque", "pl": "pięć", "lvl": 0, "learned": False}
]